{
  try {
    return function.apply(future.get());
  }
 catch (  ExecutionException e) {
    throw (Exception)e.getCause();
  }
}
