{
  int attempts=3;
  BackoffExponentiallyAndRetryOnThrowableCallable<String> backoff=new BackoffExponentiallyAndRetryOnThrowableCallable<String>(ResourceNotFoundException.class,50l,500l,attempts,mock);
  expect(mock.call()).andThrow(new ResourceNotFoundException()).times(attempts);
  replay(mock);
  try {
    backoff.call();
    fail();
  }
 catch (  ResourceNotFoundException e) {
  }
  verify(mock);
}
