{
  Function<Exception,Object> function=new ReturnFalseOn5xx();
  RuntimeException exception=new RuntimeException();
  try {
    function.apply(exception);
  }
 catch (  Exception ex) {
    assertEquals(ex,exception);
  }
}
